// src/lib/data.js

// --- PERSONAL METADATA (For SEO & Contact) ---
export const personalMeta = {
  name: "Vikrant Yadav",
  title: "Architect & Creative Developer",
  description: "Avant-garde architecture and digital experiences. Exploring the void between raw materiality and code.",
  email: "vikrant.yadav1401@gmail.com", 
  socials: {
    instagram: "https://instagram.com/yourhandle", 
    linkedin: "https://linkedin.com/in/yourhandle",
    twitter: "https://twitter.com/yourhandle",
  },
};

// --- ARCHITECTURAL PROJECTS ---
export const architecturalProjects = [
  {
    id: "the-void",
    title: "The Void",
    projectType: "Professional", 
    category: "Residential",
    year: "2024",
    location: "Jaipur, Rajasthan",
    area: "4,500 sq.ft",
    status: "Completed",
    description: "A brutalist exploration of light and shadow in the heart of Jaipur.",
    longDescription: "Located in the arid landscape of Rajasthan, this project seeks to create a microclimate within its walls. Using raw concrete and local stone, the structure acts as a shield against the harsh sun. The internal courtyards are designed to celebrate the monsoon rain while rejecting the summer heat. Every opening is a calculated decision to admit light without heat, framing the sky rather than the chaotic street.", 
    heroImage: "/assets/9.jpg", 
    coverImage: "/assets/9.jpg", 
    gallery: [
      "/assets/9.jpg", 
      "/assets/11.jpg", 
      "/assets/12.jpg",
      "/assets/KS1.jpg"
    ],
    isFeatured: true, 
  },
  {
    id: "azure-sky",
    title: "Azure Sky",
    projectType: "Competition",
    category: "Commercial",
    year: "2023",
    location: "Mumbai, India",
    area: "12,000 sq.ft",
    status: "Concept",
    description: "Vertical gardens meeting the urban skyline.",
    longDescription: "Azure Sky redefines the commercial high-rise by integrating breathing green spaces into the vertical fabric of Mumbai. The tower functions as a living organism, filtering air and providing respite from the dense urban jungle below.",
    heroImage: "/assets/9.jpg",
    coverImage: "/assets/9.jpg",
    gallery: ["/assets/R5.jpg", "/assets/R5.jpg"],
    isFeatured: true,
  },
  {
    id: "concrete-dreams",
    title: "Concrete Dreams",
    projectType: "Academic",
    category: "Urban",
    year: "2024",
    location: "New Delhi",
    area: "Site Scale",
    status: "Thesis",
    description: "Reimagining public infrastructure as social spaces.",
    longDescription: "A thesis project exploring how brutalist infrastructure can be softened and humanized to create vibrant community hubs in the center of the capital.",
    heroImage: "/assets/KS6.jpg",
    coverImage: "/assets/KS6.jpg",
    gallery: ["/assets/9.jpg", "/assets/12.jpg"],
    isFeatured: true,
  },
  {
    id: "desert-rose",
    title: "Desert Rose",
    projectType: "Professional",
    category: "Landscape",
    year: "2022",
    location: "Jaisalmer",
    area: "10 Acres",
    status: "Under Construction",
    description: "Sustainable landscaping for a luxury desert resort.",
    longDescription: "Utilizing xeriscaping techniques and native flora to create a lush oasis that respects the water scarcity of the Thar Desert.",
    heroImage: "/assets/12.jpg",
    coverImage: "/assets/12.jpg",
    gallery: ["/assets/KS1.jpg", "/assets/KS7.jpg"],
    isFeatured: true,
  },
  {
    id: "silent-hill",
    title: "Silent Hill",
    projectType: "Academic",
    category: "Residential",
    year: "2021",
    location: "Manali",
    area: "3,000 sq.ft",
    status: "Concept",
    description: "A retreat designed to frame the Himalayan peaks.",
    longDescription: "Perched on a steep slope, this residence minimizes its footprint while maximizing views. The design emphasizes thermal comfort in a cold climate using passive solar heating.",
    heroImage: "/assets/KS1.jpg",
    coverImage: "/assets/KS1.jpg",
    gallery: ["/assets/9.jpg", "/assets/9.jpg"],
    isFeatured: false,
  },
  {
    id: "urban-pulse",
    title: "Urban Pulse",
    projectType: "Competition",
    category: "Commercial",
    year: "2023",
    location: "Bangalore",
    area: "8,000 sq.ft",
    status: "Runner Up",
    description: "A mixed-use hub for the tech generation.",
    longDescription: "A dynamic workspace proposal that blurs the line between work and play, featuring modular spaces that adapt to the changing needs of a startup ecosystem.",
    heroImage: "/assets/GR11.jpg",
    coverImage: "/assets/GR11.jpg",
    gallery: ["/assets/11.jpg", "/assets/12.jpg"],
    isFeatured: false,
  },
];

// --- WEB DEVELOPMENT PROJECTS ---
export const webProjects = [
  {
    id: "discover-arch",
    title: "DiscoverArch Platform",
    techStack: ["Next.js", "Tailwind CSS", "Supabase"],
    description: "A competition hosting platform for architects with real-time submissions and jury evaluation.",
    liveLink: "https://discoverarch.com", 
    repoLink: "https://github.com/yourusername/discoverarch", 
    image: "/assets/1030.png", 
  },
  {
    id: "portfolio-v1",
    title: "Minimal Portfolio",
    techStack: ["React", "GSAP", "Framer Motion"],
    description: "My first iteration of a portfolio focusing on smooth scroll interactions and WebGL distortions.",
    liveLink: "#",
    repoLink: "#",
    image: "/assets/12.jpg",
  },
  {
    id: "threejs-playground",
    title: "Three.js Experiments",
    techStack: ["Three.js", "R3F", "WebGL"],
    description: "A collection of 3D architectural visualizations rendered directly in the browser.",
    liveLink: "#",
    repoLink: "#",
    image: "/assets/KS1.jpg",
  },
];